import json

bios = {
    "antonio-medina": "Antonio Medina Serrano (Madrid, 1944). Estudió en la Escuela de Cerámica y Bellas Artes de San Fernando. Especializado en el género costumbrista, se vio influenciado por su trabajo restaurando obras del siglo XIX (Fortuny, Madrazo). Su estilo se caracteriza por un trazo seguro, brillante colorido y una rica fuerza evocadora de época, abordando también paisajes y retratos con óleo y acuarela. Desde 1983 ha realizado numerosas exposiciones individuales y colectivas con gran éxito de crítica y público.",
    "antonio-lago-rivera": "Antonio Lago Rivera (La Coruña, 1916 - París, 1990). Reconocido pintor gallego afincado en París. Su obra abarca principalmente pintura y obra sobre papel (acuarela, tinta). A lo largo de su carrera ha expuesto en múltiples galerías, consolidando un estilo personal caracterizado por la soltura de su trazo y expresividad técnica.",
    "antonio-garcia-patino": "Antonio García Patiño (La Coruña, 1932-2010). Artista polifacético cuya obra se divide en cuatro períodos. Su 'época negra' refleja influencias de Goya, Tàpies o El Greco. En los 60 abrazó el 'karmatismo' en Barcelona, seguido de un 'período blanco' centrado en figuras hieráticas y geométricas sin volumen. Finalmente, desarrolló series temáticas y esculturas. Expone desde 1957, y su obra está en prestigiosas colecciones como el MACBA, Caixa Galicia y el Parlamento Gallego.",
    "adolfo-barnatan": "Adolfo Barnatán (París, 1951). Afincado en Madrid, inició su carrera en los 70 destacando por un dibujo minucioso. En 1994 su obra experimentó un salto hacia la escultura y formatos monumentales, investigando óleos y acrílicos. Desde 1997 es pionero en el diseño de 'Joyas de autor', fusionando mitología y misticismo en materiales como ébano y oro. Expone habitualmente en ARCO y ferias internacionales. Su obra pertenece a colecciones como el MNCARS y Fundación 'la Caixa'.",
    "ana-laura-alaez": "Ana Laura Aláez (Bilbao, 1964). Destacada artista contemporánea española, se autodefine como 'arquitecta de emociones'. Desde su debut en el Espai 13 de la Fundació Joan Miró (1992), su obra es una constante investigación espacial e identitaria. Su lenguaje incluye diseño, instalación, fotografía y música. Ha expuesto en el Palais de Tokyo, Museo Guggenheim Bilbao, MUSAC y representó a España en la Bienal de Venecia 2001. Su innovador estilo la ha consolidado a nivel mundial.",
    "aitor-ortiz": "Aitor Ortiz (Bilbao, 1971). Fotógrafo de prestigio internacional, trabaja con el espacio arquitectónico, la luz y la industria como elementos cognitivos. Ha documentado el proceso del Guggenheim Bilbao y publicado monografías en Hatje Cantz. Su trabajo cuestiona la percepción visual mediante estructuras latentes. Galardonado con el Premio ABC y el Villa de Madrid, expone asiduamente en ARCO, Paris Photo y Art Basel. Su obra está en el MNCARS, Guggenheim e IVAM.",
    "carlos-diez-bustos": "Carlos Díez Bustos (Madrid, 1959). Formado en dibujo y grabado en Madrid y Edimburgo. Su prolífica obra indaga en visiones arquitectónicas, realismo urbano, desnudos y naturalezas muertas. Experimenta con expedientes sonoros y silencios, combinando pintura y obra gráfica. Ha expuesto en galerías como Ansorena y Clérigos, así como en Art Miami y London Art Fair. Su obra forma parte de colecciones institucionales nacionales e internacionales.",
    "baltazar-torres": "Baltazar Torres (Portugal, 1961). Destacado artista internacional y profesor de Bellas Artes en la Univ. Católica de Portugal. Su trabajo, que fusiona reflexión conceptual y ejecución meticulosa, se ha exhibido en más de cincuenta individuales por Europa. Su obra indaga en la relación entre el individuo, el entorno y la estructura social, con instalaciones y esculturas características. Está representado en colecciones como Culturgest, IVAM, CGAC y CAC Málaga.",
    "antonio-beneyto": "Antonio Beneyto (Albacete, 1934 - Barcelona, 2020). Escritor, pintor y escultor español, maestro del mundo onírico y máximo representante del surrealismo contemporáneo y el postismo de posguerra. Su obra, poblada de criaturas híbridas y monstruosas con gran dosis de humor e ironía, explora el inconsciente y la metafísica. Dirigió las revistas 'La Esquina' y 'Barcarola'. Su prolífica obra plástica integra el MACBA y el Museo de Albacete, entre otras instituciones.",
    "carlos-macia": "Carlos Maciá (Lugo, 1977). Licenciado en Bellas Artes por la Univ. Politécnica de Valencia, su obra es una exploración incesante del color y el espacio urbano. Desarrolla su práctica artística a través de la pintura, el grafiti y la intervención directa en el espacio arquitectónico, alterando la percepción del espectador. Ha expuesto individualmente en el MARCO de Vigo, Fundación Luis Seoane y en destacadas galerías nacionales e internacionales.",
    "angel-masip": "Ángel Masip (Alicante, 1977). Destacado artista contemporáneo de su generación, desarrolla una profunda investigación pictórica y conceptual en torno al orden y la entropía. Galardonado con el Premio Pilar Juncosa de la Fundación Joan Miró y becado por la Academia de España en Roma. Expone habitualmente en ARCO y JustMad. Su obra entrelaza la pintura abstracta con nuevas narrativas visuales, figurando en el MUSAC y la Fundación Sa Nostra.",
    "antonio-socias": "Antoni Socías Albaladejo (Inca, 1955). Artista multidisciplinar que transita con soltura por la pintura, fotografía, escultura y el collage. Evolucionó del hiperrealismo fragmentario al expresionismo figurativo y land art, profundizando en dicotomías como orden-desorden y construcción-destrucción. Su rica producción desafía constantemente el lenguaje artístico. Ha expuesto en el Casal Solleric, Es Baluard y ferias internacionales como Colonia o Los Ángeles.",
    "bernardi-roig": "Bernardí Roig (Palma de Mallorca, 1965). Considerado uno de los creadores españoles más relevantes a nivel mundial. Su obra es una profunda reflexión sobre la luz, la ceguera, la memoria y el aislamiento del ser humano contemporáneo, materializada frecuentemente a través de esculturas de escayola blanca enfrentadas a tubos fluorescentes. Ha exhibido en The Phillips Collection, Bienal de Venecia, CA’ PESARO y el Museo Nacional de Escultura.",
    "carlos-leon": "Carlos León Escudero (Ceuta, 1948). Figura clave del expresionismo abstracto español e introductor del movimiento 'Support-surfaces'. Su pintura, matérica y de intensa gestualidad, posee un innegable poder evocador. Galardonado con la Medalla de Oro al Mérito en las Bellas Artes (2022) y el Premio Arte y Mecenazgo (2016). Tras residir en París y Nueva York, su trayectoria internacional le ha llevado a exponer en la Bienal de Venecia y contar con obra en el MNCARS.",
    "antonio-galan-tono": "Antonio Galán Fuentes 'Tono' (Santiago de Compostela, 1967). Artista polifacético especializado en procedimientos pictóricos, pintura mural, grabado y escultura. Formado con Martín Chirino, su obra es un ejercicio de rigor técnico y abstracción poética. Desarrolla su actividad también en el humor gráfico y la restauración. Ha participado en el Foro Atlántico y pertenece a colecciones institucionales como ABANCA y el MAC de Marbella.",
    "anton-patino": "Antón Patiño (Monforte de Lemos, 1957). Co-fundador del colectivo Atlántica, que renovó la plástica gallega en los 80. Su obra fusiona expresionismo simbólico, gestualismo y una profunda vinculación con el paisaje gallego, a través de la saturación de color y signos enigmáticos. Con gran proyección internacional, ha protagonizado retrospectivas en el CGAC y el Centro Conde Duque. Es además un destacado teórico contemporáneo.",
    "antonio-murado": "Antonio Murado (Lugo, 1964). Pintor de gran proyección internacional residente en Nueva York. Su estilo se distingue por el dominio técnico de las veladuras, la abstracción lírica y una delicada sensibilidad por texturas y elementos naturales. Ganador del Premio L’Oréal, su cotizada obra se ha expuesto en EE.UU., Australia o Japón, y se integra en colecciones del MNCARS, Patrimonio Nacional y el Chase Manhattan Bank.",
    "arturo-prins": "Arturo Prins (Buenos Aires, 1972). Artista polifacético, cineasta y pintor residente en Madrid. Becado en Dinamarca y vinculado al DOGMA 95, su inquietud creativa abarca documentales nominados a los Goya y una extensa obra plástica. En su pintura explora la explosión del color y el dinamismo gestual abstracto. Ha sido galardonado en múltiples certámenes nacionales, exponiendo su pintura por toda España.",
    "antonio-rojas": "Antonio Rojas Peinado (Tarifa, 1962). Destacado pintor figurativo cuyo estilo se enmarca en un realismo poético y metafísico. Su obra destaca por paisajes limpios, horizontes marítimos, juegos de sombras y composiciones arquitectónicas evocadoras. Utiliza habitualmente técnica mixta, acrílicos y collage, creando atmósferas de profunda serenidad. Cuenta con un extenso recorrido expositivo y reconocimiento crítico.",
    "calo-carratala": "Calo Carratalá (Valencia, 1959). Pintor de marcado carácter paisajístico. Su obra destaca por sus intensas expediciones por la Amazonia, Noruega o Los Alpes, plasmando la majestuosidad de la naturaleza en dibujos y óleos con una técnica rigurosa y un profundo respeto por el entorno salvaje. Expone asiduamente en España y prestigiosas ferias de arte internacionales.",
    "angel-mateo-charris": "Ángel Mateo Charris (Cartagena, 1962). Pintor español vinculado a la línea figurativa neo-pop, fuertemente influido por el cómic, el cine y la historia del arte. Su estilo colorista y narrativo está cargado de ironía y sutiles referencias culturales. Es uno de los artistas más reconocidos de su generación, con obra en el MNCARS, el IVAM y múltiples museos de arte contemporáneo.",
    "amaya-gonzalez-reyes": "Amaya González Reyes (Sanxenxo, 1979). Creadora visual gallega cuya polifacética producción se mueve entre la pintura, el dibujo, la instalación y la performance. En su obra explora las relaciones interpersonales y la ironía del día a día, desarrollando una estética muy personal, libre, íntima y profundamente contemporánea.",
    "alejandro-carro": "Alejandro Carro. Artista español contemporáneo cuya obra pictórica y gráfica destaca por un lenguaje muy personal, de carácter sintético y profundamente expresivo, participando activamente en el circuito de las galerías de arte actuales.",
    "ana-fernandez": "Ana Fernández. Creadora visual que aborda la figura femenina y la construcción de la identidad a través de un prisma figurativo marcadamente expresionista, destacando por su especial sensibilidad para el retrato psicológico y un uso potente del color."
}

with open('web/src/data/artists.json', 'r') as f:
    artists = json.load(f)
    
count = 0
for artist in artists:
    if artist['id'] in bios:
        artist['biography'] = bios[artist['id']]
        count += 1
        
with open('web/src/data/artists.json', 'w') as f:
    json.dump(artists, f, indent=2, ensure_ascii=False)
    
print(f"Rewrote {count} biographies successfully!")
