import json

bios = {
    "enrique-larroy": "Enrique Larroy (Zaragoza, 1954). Artista autodidacta con una consolidada trayectoria desde 1973. Becario de la Casa de Velázquez en Madrid (1992-94) y de la Academia Española de Bellas Artes de Roma (1994-95). En 1999 fue ganador del prestigioso XV Premio de Pintura L'Oréal. Su pintura se mueve entre la figuración pop y el realismo irónico, con una paleta vibrante y composiciones que juegan con la percepción del espectador. Ha participado en ferias internacionales como ARCO, ArtSantander, Art Toronto y Art Miami.",
    "enrique-martinez-cubells": "Enrique Martínez Cubells (Madrid, 1874 - Málaga, 1947). Pintor español, hijo del también pintor Salvador Martínez Cubells, restaurador del Museo del Prado. Formado en la Real Academia de Bellas Artes de San Fernando, destacó como retratista, paisajista y pintor de escenas costumbristas. Su estilo, de factura académica y luminista, conecta con la tradición pictórica española del cambio de siglo. Su obra está representada en museos y colecciones institucionales.",
    "eulalia-valdosera": "Eulàlia Valdosera (Vilafranca del Penedès, 1963). Artista conceptual y pionera del arte feminista en España, trabaja con fotografía, vídeo, instalación y performance. Su obra explora el cuerpo femenino, la identidad y las relaciones de poder a través de proyecciones lumínicas y sombras. Representó a España en la Bienal de Venecia (2001). Galardonada con el Premio Nacional de Artes Plásticas (2002), su obra pertenece al MNCARS, MACBA y Centre Pompidou.",
    "eva-lootz": "Eva Lootz (Viena, 1940). Artista plástica austriaca afincada en España desde 1967. Formada en Bellas Artes, Filosofía y Dirección de Cine, su obra abarca escultura, instalación, dibujo y vídeo. Trabaja con materiales como mercurio, arena y sal, creando piezas post-minimal de profunda carga poética. Premio Nacional de Artes Plásticas (1994), ha expuesto en la Fundación Joan Miró, CGAC y el Museo de Arte Moderno de Bogotá. Su obra integra las principales colecciones públicas españolas.",
    "fernando-bayona": "Fernando Bayona (Montizón, Jaén, 1980). Fotógrafo y artista visual formado en Bellas Artes (Granada) y Fotografía (NABA, Milán). Su obra, de marcado carácter escenográfico y narrativo, recrea tableaux vivants cargados de simbolismo, ironía y referencias al imaginario religioso y circense. Ha participado en PhotoEspaña y SegoviaFoto, exponiendo internacionalmente en Suiza, EE.UU. y Holanda. Ha recibido múltiples becas y reconocimientos por su singular universo visual.",
    "fernando-sanchez-calderon": "Fernando Sánchez Calderón (Valladolid, 1951 – 2016). Pintor y docente universitario. Licenciado en Bellas Artes (Madrid, 1975), representó a España en la XVI Bienal de São Paulo (1977) y participó en la III Bienal del Cairo (1988). Compaginó su producción artística con la docencia en la Universidad de Salamanca. Su obra, que transita entre la abstracción geométrica y la investigación matérica, está presente en el MNCARS, el Congreso de los Diputados y el MACUF.",
    "fernando-yanez": "Fernando Yáñez (Lugo, 1978). Licenciado en Bellas Artes por la Universidad de Vigo y MFA por la Complutense. Su pintura se caracteriza por atmósferas densas y silenciosas que evocan espacios de vacío y espiritualidad. Series como 'Requiem' y 'Lares' exploran la luz como materia expresiva. Ha expuesto individualmente en el Museo Provincial de Lugo y en galerías de Madrid y Galicia, participando en ferias como ArteSantander.",
    "florencio-alonso": "Florencio Alonso (Estella, Navarra, 1961). Artista navarro cuya obra transita entre la pintura, la instalación y el videoarte. Su producción reflexiona sobre la memoria colectiva, el silencio y las víctimas. Ha expuesto en el Museo Jorge Oteiza, el Museo de Navarra y el Parlamento Europeo de Bruselas. Participó en ARCO con la Galería Moisés Pérez de Albéniz y en DIVA (Nueva York). Su obra está en la colección del Museo de Navarra.",
    "francisco-otero-besteiro": "Francisco Otero Besteiro. Pintor y acuarelista gallego, cuya obra destaca por la delicadeza de su trazo y una poética intimista aplicada al retrato, las figuras marineras y los paisajes. Su técnica de acuarela sobre papel, de formato reducido, alcanza una expresividad notable. Representado en colecciones privadas y galerías de Galicia.",
    "francisco-reina": "Francisco Reina (Sevilla, 1979). Fotógrafo contemporáneo formado en Bellas Artes (Sevilla) y dirección de fotografía (EFTI, Madrid). Su obra, que explora estados alterados de percepción y la memoria, ha sido exhibida internacionalmente en galerías de Rotterdam, Nueva York y Ámsterdam. Ha participado en festivales como Noorderlicht y Naarden (Holanda) y en ferias como Estampa y ArteSantander. Ganador del VIII Premio Purificación García.",
    "german-gomez": "Germán Gómez. Artista visual español de amplia proyección internacional. Su obra fotográfica y pictórica explora la identidad, el cuerpo y las fronteras entre lo real y lo ficticio. Ha expuesto individualmente en el Centro Niemeyer, PhotoEspaña, la Bienal de Alejandría y galerías de Bogotá, Filadelfia, Bielefeld y Miami. Participante habitual en ARCO, su trabajo ha sido reconocido con el Premio Revelación PhotoEspaña.",
    "gino-rubert": "Gino Rubert (México, 1969). Artista hispano-mexicano formado en Parsons (Nueva York) y Bellas Artes (Barcelona). Su obra, que abarca pintura, escultura, dibujo y vídeo, conjuga un figurativismo exquisito con una atmósfera onírica y sensual de raíz literaria. Ganador del Premio de Pintura Joven de la Sala Parés (1993), sus ilustraciones para la trilogía 'Millennium' de Stieg Larsson le dieron reconocimiento mundial. Ha expuesto en Tokio, Berlín, Nueva York y Roma.",
    "gonzalo-perez-mata": "Gonzalo Pérez Mata. Fotógrafo contemporáneo español. Máster en Fotografía (EFTI) y Licenciado en Comunicación Audiovisual (CEU). Su obra explora el paisaje urbano y la condición humana a través de una mirada documental y poética. Ha expuesto en el IVAM, el Círculo de Bellas Artes de Madrid, Dubái y el Palacio de Minería de México. Su obra está representada en la colección del IVAM.",
    "guillermo-mora": "Guillermo Mora (Alcalá de Henares, 1980). Artista contemporáneo español cuya práctica desafía los límites de la pintura expandiéndola al espacio tridimensional. Trabaja con acrílicos, pigmentos y materiales industriales para crear obras escultóricas que cuestionan la naturaleza del cuadro. Ganador del Premio Generaciones (2013), ha expuesto en el CA2M, Matadero Madrid y en ferias como ARCO y Art Basel Miami.",
    "hannah-collins": "Hannah Collins (Londres, 1956). Fotógrafa y artista visual británica de reconocimiento internacional. Su obra, frecuentemente en gran formato, documenta espacios abandonados, paisajes humanos y la huella del tiempo sobre la materia. Trabaja con gelatina de plata y técnicas analógicas. Ha expuesto en la Tate Modern, el Centre Pompidou y el MACBA. Finalista del Turner Prize (1993), su obra pertenece a las más importantes colecciones de arte contemporáneo.",
    "hector-orruno": "Héctor Orruño (Vitoria, 1980). Licenciado en Bellas Artes por la Universidad del País Vasco, con formación en el taller de Juan Uslé (Fundación Botín). Su obra pictórica explora la tensión entre lo orgánico y lo tecnológico, con composiciones cromáticamente potentes. Ganador del Premio Generación 2004 (Caja Madrid) y del Primer Premio del Certamen de Pintura de Amurrio. Ha expuesto en Montehermoso (Vitoria) y en La Fresh Gallery (Madrid).",
    "iago-eireos": "Iago Eireos (Lugo, 1980). Licenciado en Bellas Artes por la Universidad de Vigo y técnico superior en Grabado y Fotografía Artística. Su obra explora la memoria del paisaje a través de técnicas mixtas, fotografía e instalación, creando capas de significado sobre territorios transformados. Ha expuesto individualmente en la Fundación Antonio Gala, el Centro Cultural de Ourense y galerías de Florencia y Barcelona. Su trabajo itineró por España, Portugal e Italia.",
    "isabel-tallos": "Isabel Tallos (Madrid, 1983). Artista visual y fotógrafa. Licenciada en Bellas Artes (UCM), Máster en Fotografía (EFTI) y becaria Roberto Villagraz. Su obra combina fotografía, pintura y nuevas tecnologías para explorar la percepción del espacio y la identidad. Ha recibido formación de Daniel Canogar y Antonio López García. Ha expuesto en Alemania, República Checa y diversas salas españolas, consolidando un lenguaje visual profundamente contemporáneo.",
    "ismael-iglesias-serrano": "Ismael Iglesias Serrano (Durango, 1974). Licenciado en Bellas Artes (UPV) en Pintura y Audiovisuales. Formado en los talleres de Juan Uslé (Botín) y Markus Lüpertz. Su obra fusiona pintura, nuevas tecnologías y medios digitales, creando paisajes hipnóticos y vibrantes que dialogan con la cultura visual contemporánea. Ha expuesto en la Delfina Foundation (Londres), Galería ADN (Barcelona), CAFAM (Beijing) y en múltiples espacios nacionales.",
    "javier-pagola": "Javier Pagola (San Sebastián, 1955). Dibujante y pintor que ha hecho del dibujo su principal arma creativa, inspirándose en El Bosco, Antonio Saura y el expresionismo. Su universo de seres extraños combina lo grotesco con lo poético. Becado por la Academia de Roma y la Fundación Botín, ha ganado el Premio Ciudad de Albacete y el Internacional de Valdepeñas. Ha ilustrado más de quince libros y su obra está en museos españoles y la Fundación de Menil (Houston).",
    "jesus-otero-yglesias": "Jesús Otero-Yglesias (Lugo, 1963). Artista personal e inconfundible, su peculiar paisajismo mezcla influencias surrealistas (Magritte) con una lírica idealización de la naturaleza gallega. Becado por la Fundación Miró y Sargadelos, ha expuesto desde 1986 en España, Francia, Bélgica, Alemania, Japón y Portugal. Participó en la Bienal de Pontevedra y la Mostra Unión Fenosa. Su obra está en los principales museos gallegos y colecciones internacionales.",
    "diego-casado-cerezo": "Diego Casado Cerezo (Sevilla, 1958). Pintor contemporáneo cuya obra reflexiona sobre el paisaje, la memoria y el espacio interior. Series como 'La casa del alma' o 'Espacio oculto' revelan un lirismo abstracto de gran delicadeza cromática. Su técnica combina la materia pictórica con atmósferas contemplativos de profunda serenidad. Ha expuesto en diversas galerías nacionales, consolidando un sólido prestigio entre la crítica especializada."
}

with open('web/src/data/artists.json', 'r') as f:
    artists = json.load(f)

count = 0
for artist in artists:
    if artist['id'] in bios:
        artist['biography'] = bios[artist['id']]
        count += 1

with open('web/src/data/artists.json', 'w') as f:
    json.dump(artists, f, indent=2, ensure_ascii=False)

print(f"Rewrote {count} biographies.")

# Final stats
total_works = sum(len(a['works']) for a in artists)
pending = [a['name'] for a in artists if 'pendiente' in a.get('biography','').lower()]
print(f"Total: {len(artists)} artists, {total_works} artworks")
if pending: print(f"Still pending bio: {pending}")
else: print("All biographies complete!")
